# Generated by Django 4.2.4 on 2023-11-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='foto',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
